cc_test(
    name = "BitVectorTest",
    srcs = ["BitVectorTest.cpp"],
    deps = [
        "//phylokit:BitVector",
        "@catch2//:main",
    ],
)

cc_test(
    name = "NewickTest",
    srcs = ["newickTest.cpp"],
    deps = [
        "//phylokit:newick",
        "@catch2//:main",
    ],
)
